### ISSUE TITLE
Implement JWT Authentication with B2C Commerce's Account Manager.

### ISSUE THREAD

**Issue by b2csolutionarchitect** [sfb2csolutionarchitects/b2c-crm-sync#117]
### Issue Summary

> In the spirit of transparency, this issue is significant and a **blocker for production implementations**.  Please be mindful that this issue -- without a workaround or alternate approach -- should prevent b2c-crm-sync from being deployed in production.

Currently, we have an intermittent but repeatable issue where the Salesforce platform is unable to retrieve an authToken from the B2C Commerce AccountManager.  This typically occurs 24-25 hours after the initial setup of b2c-crm-sync.  The root cause of this is that the Salesforce authProvider is leveraging a user-base authenticationFlow.  This flow prevents a refreshToken from being requested from Account Manager.

- When we invoke a REST API call to B2C Commerce, we leverage a Named Credential associated to our Account Manager authProvider.  The namedCredential / authProvider are responsible for requesting the authToken from AccountManager.
- When a scratchOrg is first setup, editing the namedCredential instantiates the initial authProcess -- and as part of this, an authToken is provided by Account Manager to the Salesforce Platform.
- Account Manager authTokens expire in 30 minutes; their refreshTokens expire in 24 hours.
- When the authToken expires, a refreshToken is requested and provided.  
- When the refreshToken expires, Salesforce has no way to request ANOTHER refreshToken.  

This leaves us in a position where the existing authToken has expired -- and as a result, B2C Commerce returns 401 errors for any REST API request:

```json
{
     "fault" : {
          "message" : "Unauthorized request! The access token 's1yxOnTI3IDcr6aGxVsIoU3Ugjc' is invalid.",
          "type" : "InvalidAccessTokenException",
          "arguments" : {
               "accessToken" : "s1yxOnTI3IDcr6aGxVsIoU3Ugjc"
          }
     },
     "_v" : "20.10"
}
```

> The only way to resolve this issue is to edit the namedCredential, enable the re-launch authentication flow, and save the namedCredential without making changes to its definition.  This workaround will work in a scratchOrg, but is untenable in a production environment.

### Issue Resolution
There are a number of scenarios / alternatives to explore to resolve this issue:

- [x] **Retrieve access tokens using JWT**.  Account Manager supports r[etrieving accessTokens using JWT](https://documentation.b2c.commercecloud.salesforce.com/DOC2/topic/com.demandware.dochelp/OCAPI/current/usage/OAuth.html?cp=0_15_2_23).  JWT can also be leveraged by the [Salesforce JWT Bearer Flow](https://help.salesforce.com/articleView?id=sf.remoteaccess_oauth_jwt_flow.htm&type=5).
> Explore if we can generate the AccountManager [JWT cert / details using SFDX](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_key_and_cert.htm). 
- [x] **Eliminate the need for AccountManager namedCredentials**.  Since we're rolling our own authentication, let's remove the tight coupling to managing namedCredentials.  Let's remove the management flows as well as artifacts on the object schema.
- [ ] **Manually implement token requests as separate Apex REST API Callouts**.  This is the least desirable option (the 2nd option is pretty bad as well) and last alternative to consider.  We should only consider this is the previous two options are not successful.

### Work Items
This issue will be considered done when the following activities have been completed:

### b2c-crm-sync Application Changes
- [x] Remove the authProvider from the Salesforce Platform meta-data.
- [x] Remove the dependency between our namedCredentials and the authProvider.
- [x] Refactor the object schema for B2C Instances incorporating the B2C Client ID record and formula fields.
- [x] Refactor the object schema for B2C CustomerLists incorporating the B2C Client ID record and formula fields.
- [x] Refactor the object schema for B2C Sites incorporating the B2C Client ID record and formula fields.
- [x] Refactor the b2cInstanceSetup quick-action to leverage JWT-generated authTokens.
- [x] Refactor the b2cInstance seed CustomerList / Sites quickAction.
- [x] Abstract the CustomerList / Site updates to a separate sub-flow re-usable by the b2cInstanceSetup service.
- [x] Carry forward the B2C Client ID to Sites from the parent B2C Instance
- [x] Refactor the b2cInstanceSetup service-flow to leverage JWT-generated authTokens.
- [x] Create a separate permissionSet for b2c-crm-sync.
- [x] Eliminate legacy field(s) from the B2C Instance, CustomerList, and Site customObjects

### b2c-crm-jwt application changes
- [x] Create a separate Lightning App to manage Client ID / AuthToken interactions.
- [x] Create the Client ID / AuthToken custom objects.
- [x] Implement a switch to control auditing of AuthToken requests.
- [x] Create a trigger to verify the developerCertName associated to a ClientID and alert the user if it does not exist
- [x] Audit the AuthToken request attempts for a given B2C Client ID.
- [x] Create the JWT-related classes to handle minting, cert-validation, and authRequest processing
- [x] Audit the usage for a given B2C AuthToken (incrementing individual usage counts)
- [x] Audit the usage for AuthTokens via a Future Method (vs. doing it in-line)
- [x] Add the ability to invalidate an authToken for a given B2C Client ID.
- [x] Create a separate permissionSet for b2c-crm-jwt.

### Deployment Changes
- [x] Extend the readMe.md to include guidance on how to create a self-signed cert and export it from Salesforce as a keystore.
- [x] Create a CLI command to parse the public / private keys from the Salesforce self-signed certificate JKS
- [x] Extend the custom meta-data to include configuration settings defining Account Manager authToken related configuration properties.
- [x] Extend the configuration settings meta-data to include a mapping to the Account Manager authToken configuration settings.
- [x] Audit the developerName of the keyStore for future deployment / use
- [x] Extend the .env attributes to support the SFCertificateDeveloperName argument
- [x] Extend the ReadMe.md documentation to capture the SFCertificateDeveloperName argument
- [x] Add the Account Manager url as a remote site.
- [x] Extend deployment to include the Account Manager Remote Site definition.
- [x] Eliminate the need for the AMNamedCredential; prune it from layout and flows

**Comment by b2csolutionarchitect** [comment]
@jbachelet -- please review and provide any feedback.  I'd like to use this issue summary to socialize this with other team members and get feedback on approach viability / troubleshooting paths.  Thank you! :)

**Comment by b2csolutionarchitect** [comment]
This issue has been addressed, and is included in the [v0.9.0 release-branch](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/tree/release/0.9.0).
