### ISSUE TITLE
Implement ESLint and PMD source-code analysis for Salesforce meta-data, CLI libraries, and B2C Commerce cartridges.

### ISSUE THREAD

**Issue by b2csolutionarchitect** [sfb2csolutionarchitects/b2c-crm-sync#137]
### Issue Summary
As part of hardening this codebase, we need static analysis on the codebase that can be used for each type of code-asset leveraged within b2c-crm-sync.  This includes:

- [x] Custom esLint rules for B2C Commerce cartridges informed by SFRA server-side rules
- [x] Custom esLint rules for CLI libraries supporting es6 syntax
- [x] Salesforce Apex class and trigger static analysis adhering to a set of PMD-based best practices

Let's implement rules-sets for each of these code-assets, and incrementally start correcting the highest-priority violations surfaced by code-analysis.  This is the first step towards implementing git-hooks that can be used to pre-check code prior to check-ins or pushes to an origin.

> We've implemented the esLint and PMD rules for our B2C Commerce cartridges, CLI libraries, and Salesforce assets to enforce code quality and consistency.  We'll continue to build on this.  These rules are included in the [v0.9.0 release-branch](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/tree/release/0.9.0).
